<?php

namespace Faker\Provider\ru_RU;

class Goods extends \Faker\Provider\Company
{
    protected static $goodname = array(
        'Алкалиновая батарейка КОСМОС АА(пальчиковая) 1.5V LR06 4шт. блистер',
        'Бампер(алюминий) + задняя крышка с картинкой для Apple iPhone 6 Plus/6S Plus',
        'Бампер(алюминий) + задняя крышка с картинкой для Apple iPhone 6/6S',
        'Алкалиновая батарейка КОСМОС ААА(мезинчиковая) 1.5V LR03 4шт. блистер',
        'Бампер(алюминий) + задняя крышка StylishProtect для Samsung Galaxy S6',
        'Бампер(алюминий) + задняя крышка StylishProtect для Apple iPhone 5/5S',
        'Бампер + задняя крышка(SoftTouch) StylishProtect для Apple iPhone 5/5S',
        'Бампер + задняя крышка(SoftTouch) StylishProtect для Samsung Galaxy S6',
        'Адаптер MHL (microusb->HDMI)',
        'Power Bank MP904-1 (5000mAh)',
        'Бампер DRACO VENTARE для Apple iPhone 5/5S',
        'Бампер DRACO Ducati для Apple iPhone 6',
        'Защитное стекло для Apple iPhone 4/4s',
        'Адаптер MiraScreen(Miracast,Airplay,DLNA)',
        '4K Wi-Fi Action Camera',
        'Задняя крышка с рисунком для Samsung Galaxy Note 3',
        'Задняя крышка с рисунком для Samsung Galaxy Note 4',
        'Задняя крышка с рисунком для Samsung Galaxy S6',
        'Задняя крышка с рисунком для Samsung Galaxy S5',
        'Алкалиновая батарейка AG4/LR626 Videx 1.5V (1шт)',
        'Алкалиновая батарейка AG13/LR44 Videx 1.5V (1шт)',
        'Автомобильный держатель для смартфона "Mobile Phone Holder" (макс.ширина:100мм)',
        'Автомобильный держатель Pockets',
        'Power Bank "League of Legends" (6000mAh)',
        'Mini-PC "Mini PC/TV Dongle"',
        'Зарядное устройство USB "charger travel companion es-d02" (2*2.1A+2*1.0A; max:4.2A)',
        'Power Bank "Череп" (8800mAh, 1A)',
        'Power Bank (12000mAh, 2*2.1A/5V)',
        'Power Bank "Marvel Avengers Капитан Америка" (6800mAh)',
        'Power Bank "Marvel Avengers" герои (12000mAh)',
        'Power Bank Cartoon герои (8800mAh, 1A)',
        'Power bank (2600mAh)',
        'Алюминиевый бампер для Apple iPhone 4/4S',
        'Алюминиевый бампер для Samsung Galaxy Note 4',
        'Алюминиевый бампер для Apple iPhone 5/5S',
        'Алюминиевый бампер для Apple iPhone 6 Plus',
        'Алюминиевый бампер для Samsung Galaxy S4',
        'Алюминиевый бампер для Apple iPhone 6/6S',
        'Алюминиевый бампер для Samsung Galaxy Note 3',
        'Задняя крышка Original для Samsung Galaxy Note 4',
        'Зарядное устройство для аккумулятора для Samsung Galaxy Note 3',
        'Зарядное устройство для аккумулятора для Samsung Galaxy Note 4',
        'Защитная плёнка для Apple iPhone 6 Plus',
        'Защитная плёнка для Apple iPhone 6/6S',
        'Защитное стекло для Apple iPad mini',
        'Задняя крышка для Samsung Galaxy Note 3',
        'Зарядное устройство для аккумулятора для Samsung Galaxy S4',
        'Защитная плёнка для LG G3',
        'Зарядное устройство для аккумулятора для Samsung Galaxy S5',
        'Защитное стекло для Apple iPhone 5/5S',
        'Защитная плёнка для Samsung Galaxy Note 3',
        'Защитное стекло для Apple iPad Air',
        'Защитная плёнка для Samsung Galaxy Note 4',
        'Защитное стекло для Apple iPhone 6 Plus',
        'Защитное стекло для Apple iPhone 6/6S',
        'Защитное стекло для Apple iPhone 6 Plus с цветной рамкой',
        'Защитное стекло для Apple iPhone 6/6S с цветной рамкой',
        'Защитная плёнка для Samsung Galaxy S3',
        'Защитная плёнка для Apple iPhone 5/5S',
        'Защитная плёнка для Apple iPhone 4/4S',
        'Защитная плёнка для Samsung Galaxy S4',
        'OTG TF Card Reader',
        'OTG Smart Micro USB Cable',
        'Mini Digital Strap OTG',
        'Автомобильная зарядка (метал, 2 out, 3.1A)',
        'Автомобильная зарядка на 2USB Dual USB mini Senior Charger ES-11  2 out, 3.1A)',
        'Автомобильная зарядка на 3USB ES-07  2 out, 3.1A max)',
        'Автомобильная зарядка на 2USB ES-6S ( 2 out, 3.1A, кабель в комплекте)',
        'Power Bank(10400mAh) + Wireless Charger(USB-2.1A, Wireless-1A)',
        'Адаптер HDMI - microHDMI',
        'Беспроводная зарядка Qi(круг)',
        'Беспроводная зарядка Fantasy',
        'Адаптер HDMI - miniHDMI',
        'Адаптер HDMI - miniHDMI + microHDMI',
        'Адаптер Microusb->lightning',
        'Адаптер 2 в 1 (короткий, жёсткий)',
        'AUX 1.8м цветной',
        'AUX 1.2м белый',
        'Защитная плёнка для Samsung Galaxy S5',
        'Зарядное устройство E-Strong USB Charger ES-D09 2.4A(1*2.4A+1*1A)',
        'Зарядное устройство E-Strong USB Charger ES-D11 2.4A(1*2.4A+1*1A)',
        'Bluetooth Мини Клавиатура',
        'Задняя крышка для Samsung Galaxy Note 4',
        'Задняя крышка для Samsung Galaxy S4',
        'Power Bank солнечный Microfins',
        'Адаптер питания на 2 USB порта',
        'Алюминиевый бампер для Samsung Galaxy S3',
        'Защитная плёнка для Apple iPad mini',
        'Автомобильное зарядное устройство (5V = 3.1А, 2 usb, цветная)',
        'Автомобильное зарядное устройство (5V = 3.1А, 2 usb, белая)',
        'Аккумулятор для Samsung GALAXY S4',
        'Аккумулятор для Samsung GALAXY Note 3',
        'Аккумулятор для Samsung GALAXY Note 4',
        'Аккумулятор для Samsung GALAXY S5',
        'Power Bank с солнечной батареей Solar Charger (5000mAh, 5V/1A)',
        'Wireless Qi Charger Receiver(универсальный)',
        'Адаптер питания Apple USB 12W',
        'Задняя крышка для Samsung Galaxy S5',
        'Защитное кольцо на объектив камеры для Apple iPhone 6/6S',
        'Защитное кольцо на объектив камеры для Apple iPhone 6 Plus',
        'Накладка GUOBINFEN leisure series(пластик) на Apple iPhone 6 Plus /6S Plus',
        'Накладка алюминиевая Tropicana relief series на Apple iPhone 6 Plus/6S Plus',
        'Накладка GUOBINFEN leisure series(пластик) на Apple iPhone 6/6S',
        'Накладка алюминиевая Tropicana relief series на Apple iPhone 6/6S',
        'Литиевая батарейка Спутник CR2032 3V (1шт)',
        'Литиевая батарейка GP LITHIUM CR2016/DL2016 3В (1шт)',
        'Накладка алюминиевая Tropicana relief series на Apple iPhone 5/5S',
        'Колонка Super Bass Portable Y8',
        'Чехол GUOBINFEN Fantasy Trip(SoftTouch мягкий пластик) с рисунком для Apple iPhone 6/6S',
        'Чехол GUOBINFEN Fantasy Trip(SoftTouch мягкий пластик) с рисунком для Apple iPhone 6 Plus/6S Plus',
        'Колонка PILL SPEAKER ATS-829 (цветомузыка)',
        'Колонка mini Speaker S605 с подставкой под смартфон',
        'Колонка mini Speaker S204',
        'Силиконовый чехол для Monster Beats Pill',
        'Флешка-игрушка 8GB',
        'Наклейки на клавиатуру черные с белыми русскими и латинскими буквами',
        'Наклейки на клавиатуру белые с чёрными русскими и латинскими буквами',
        'Липкий коврик в а/м для смартфона (бол, 18x12.5)',
        'Липкий коврик в а/м для смартфона (мал, 14x8)',
        'Наушники bluetooth NK-850',
        'Наушники Bluetooth Stereo Headset',
        'Устройство передачи медиаконтента на ТВ "HDMI Dongle"',
        'Цветное защитное стекло для Apple iPhone 5/5S(комплект)',
        'Устройство передачи медиаконтента на ТВ "Wecast"',
        'Наушники bluetooth Stereo Headphones S460',
        'Цветное защитное стекло для Apple iPhone 6 Plus/6S Plus(комплект)',
        'Смарт-часы Q7S',
        'Наушники bluetooth NK-8001BT',
        'Литиевая батарейка GP LITHIUM CR2025/DL2025 3В (1шт)',
        'Мини bluetooth наушник S530',
        'Наушники для спорта Tangshu i008',
        'Наушники с бусинками, вкладыши',
        'Наушники светящиеся',
        'Наушники для спорта(за ухо)',
        'Наушники алюминевые вклавыши',
        'Наушники с красной полосой',
        'Силиконовый прозрачный чехол Babox для Apple iPhone 6/6S',
        'Силиконовый прозрачный чехол Guobinfen для Apple iPhone 6/6S',
        'Наушники на молнии',
        'Наушники Ufeeling',
        'Наушники обычные вкладыши',
        'Силиконовый прозрачный чехол Babox для Apple iPhone 6 Plus/6S Plus',
        'Силиконовый прозрачный чехол Guobinfen для Apple iPhone 6 Plus/6S Plus',
        'Наушники Apple EarPods (оригинал)',
        'Палка для селфи (монопод)',
        'Защитное стекло для Samsung Galaxy Note 3',
        'Защитное стекло для Samsung Galaxy Note 4',
        'Кабель Apple 30-pin на USB',
        'Колонка BOSE SoundLink mini',
        'Смарт-часы iCoui',
        'Трипод + монопод  (bluetooth)',
        'Чехол Birscon 361° для Apple iPad mini 3 (175)',
        'Смарт-часы Watch G10',
        'Чехол Element Case "Ronin" для Apple iPhone 6/6S',
        'Цветное защитное стекло для Apple iPhone 6/6S(комплект)',
        'Чехол Element Case "Ronin" для Apple iPhone 6 Plus',
        'Чехол Native Union для Apple iPhone 5/5s',
        'Спортивные наушники на шею bluetooth',
        'Фото вспышка для телефона светодиодная(jack 3.5)',
        'Накладка кожаная icarer/xoomz с отверстием под логотип для Apple iPhone 6/6S',
        'Накладка кожаная icarer/xoomz с отверстием под логотип для Apple iPhone 6 Plus/6S Plus',
        'Миниатюрный вентилятор microusb/usb/Lightning',
        'Кабель-браслет USB to microusb/Lightning',
        'Защитное стекло для Samsung Galaxy S4',
        'Защитное стекло для Samsung Galaxy S5',
        'Защитное стекло для LG G3',
        'Лента спортивная на пояс для смартфона',
        'Подставка для смартфона с кабелем',
        'Кабель-зажигалка выдвижной',
        'Переходник AUX 2->1',
        'Наклейка для Apple iPhone 6/6S',
        'Переходники для Sim-карты',
        'Кабель AUX плетёный 0.9м',
        'Кабель microusb/Lightning плетёный 1м',
        'Кабель microusb/Lightning 2 в 1 Хром',
        'Кабель microusb/lightning 2 в 1 + Амперметр/Вольтметр',
        'Колонка Mini',
        'Накладка кожаная icarer/xoomz с карманами под 3 карточки для Apple iPhone 6/6S',
        'Накладка кожаная icarer/xoomz с карманами под 3 карточки для Apple iPhone 6Plus/6S Plus',
        'Наклейка для Apple iPhone 4/4S',
        'Наклейка для Samsung Galaxy Note 4',
        'Колонка Monster Beats Pill',
        'Наклейка для Samsung Galaxy Note 3',
        'Наклейка для Apple iPhone 5/5S',
        'Чехол Element Case "Sector PRO" для Apple iPhone 6',
        'Чехол Birscon для Apple iPad Air 2 (2 створки,199)',
        'Чехол Birscon для Apple iPad mini 3 (205)',
        'Чехол Birscon для Apple iPad Air 2 (3 створки,144)',
        'Наушники Apple EarPods (цветные)',
        'Кабель для Samsung ECB-DU4EWE (1.5м)',
        'Карта памяти microsd SanDisk 32GB',
        'Карта памяти microsd SanDisk 64GB',
        'Кабель для зарядки 2-в-1 (lightning + microusb)',
        'Сетевое зарядное Apple USB Power Adapter(5V = 1A)',
        'Сетевое зарядное устройство Samsung(5.3V = 2A)',
        'Кабель Lightning/USB',
        'Кабель Lightning/USB золотой',
        'Кабель для Samsung ECB-DU4AWE (1м)',
        'Ремешок на запястье',
        'Ремешок на шею',
        'Чехол кожанный для Apple iPad Air(логотип apple на тыльной стороне)',
        'Чехол кожаный  "Crown" со стразами для Apple iPad Air',
        'Чехол кожаный  "Crown" со стразами для Apple iPad 3',
        'Чехол кожанный для Apple iPad mini(логотип apple на тыльной стороне)',
        'Чехол кожанный смарт-крышка для Apple iPad Air(вышивка с названием)',
        'Чехол кожанный смарт-крышка для Apple iPad mini(вышивка с названием)',
        'Чехол-коробочка для наушников',
        'Чехол под кожу для Apple iPhone 6 Plus/6S Plus',
        'Чехол под кожу для Apple iPhone 6/6S',
        'Чехол силиконовый жёсткий с рисунком для Samsung Galaxy Note 4',
        'Чехол силиконовый жёсткий с рисунком для Samsung Galaxy S5',
        'Чехол силиконовый прозрачный с картинкой для Apple iPhone 5/5S',
        'Чехол силиконовый жёсткий с рисунком для Apple iPhone 5/5S',
        'Чехол силиконовый жёсткий с рисунком для Apple iPhone 6/6S',
        'Чехол силиконовый жёсткий с рисунком для Samsung Galaxy S4',
        'Чехол пластиковый Soft Touch с картинкой для Apple iPhone 6 Plus/6S Plus',
        'Чехол силиконовый жёсткий (картинки под дерево) для Apple iPhone 6 Plus/6S Plus',
        'Чехол силиконовый жёсткий с рисунком для Samsung Galaxy Note 3',
        'Чехол пластиковый Soft Touch с картинкой для Apple iPhone 5/5S',
        'Чехол пластиковый Soft Touch с картинкой для Apple iPhone 6/6S',
        'Чехол силиконовый жёсткий (картинки под дерево) для Apple iPhone 6/6S',
        'Чехол силиконовый прозрачный с картинкой для Apple iPhone 6/6S',
        'Чехол силиконовый прозрачный с картинкой для Apple iPhone 6 Plus/6S Plus',
        'Чехол X-Level Mini Leather Series для Apple iPhone 5/5S',
        'Чехол деревянный для Apple iPhone 6/6S',
        'Чехол X-Level Mini Leather Series для Apple iPhone 6/6S',
        'Чехол силиконовый жёсткий с рисунком для Apple iPhone 6 Plus',
        'Чехол X-Level Mini Leather Series для Apple iPhone 6 Plus',
        'Чехол кожаный  "Crown" со стразами для Apple iPad mini',
        'Чехол силиконовый прозрачный с рисунком для Apple iPhone 5/5S',
        'Чехол силиконовый прозрачный с рисунком для Apple iPhone 6/6S',
        'Чехол силиконовый прозрачный с рисунком для Apple iPhone 6 Plus',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin для Apple iPhone 6/6S',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin для Apple iPhone 6 Plus',
        'Чехол силиконовый черный матовый для Apple iPhone 6 Plus',
        'Чехол силиконовый + пластик(тыл) с картинкой/пластик(прозрачный) для Apple iPhone 5/5S',
        'Чехол силиконовый + пластик(тыл) с картинкой/пластик(прозрачный) для Apple iPhone 6/6S',
        'Чехол Xuenair для iPhone 5/5S',
        'Чехол Xuenair для iPhone 6/6S',
        'Чехол силиконовый + пластик(тыл) с картинкой/пластик(прозрачный) для Apple iPhone 6 Plus/6S Plus',
        'Чехол-книжка Xuenair для iPhone 6/6S',
        'Чехол кожаный StylishProtection(бампер+крышка(ромб)) для Apple iPhone 5/5S',
        'Чехол пластиковый с Soft Touch Silicon Case для Apple iPhone 6/6S',
        'Чехол пластиковый с Soft Touch Silicon Case для Apple iPhone 6 Plus/6S Plus',
        'Чехол-книжка кожаный с отделами под карточки для Apple iPhone 6 Plus/6S Plus',
        'Чехол-книжка кожаный с отделами под карточки для Apple iPhone 6/6S',
        'Чехол кожанный Fashion Luxury Leather Case с 2 отделениями под карточки для Apple iPhone 6/6S',
        'Чехол-сумка кожаный DC Go-Go leater case для Apple iPhone 6/6S',
        'Чехол-книжка кожаный DC Luca leather case для Apple iPhone 6/6S',
        'Чехол-книжка кожаный DC Luca leather case для Apple iPhone 6 Plus/6S Plus',
        'Чехол-сумка кожаный DC Go-Go leater case для Apple iPhone 6 Plus/6S Plus',
        'Чехол-книжка кожаный с картинкой для Samsung Galaxy S6 edge',
        'Чехол-книжка кожаный с картинкой для Samsung Galaxy S6 edge Plus',
        'Чехол карбоновый для Apple iPhone 6/6S',
        'Чехол карбоновый для Apple iPhone 6 Plus',
        'Чехол S View Cover Samsung Galaxy Note 4',
        'Чехол-книжка кожанный с металической вставкой для Apple iPhone 6/6s',
        'Чехол силиконовый глянцевый с рисунком для Apple iPhone 6/6S',
        'Чехол силиконовый глянцевый с рисунком для Samsung Galaxy S5',
        'Чехол силиконовый глянцевый с рисунком для Apple iPhone 5/5S',
        'Чехол силиконовый глянцевый с рисунком для Apple iPhone 6 Plus',
        'Чехол силиконовый глянцевый с рисунком для Samsung Galaxy S4',
        'Чехол на ремень XL39H для Sony Xperia Z Ultra',
        'Чехол на ремень для Apple iPhone 6 Plus',
        'Чехол силиконовый прозрачный с картинкой для Samsung Galaxy S6',
        'Чехол силиконовый прозрачный с картинкой для Samsung Galaxy S6 Edge',
        'Чехол-книжка кожаный с картинкой для Samsung Galaxy S6',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin с логотипом Apple для Apple iPhone 6 Plus',
        'Чехол силиконовый прозрачный рифленый для Apple iPhone 6/6S',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin с логотипом Apple для Apple iPhone 6/6S',
        'Чехол силиконовый прозрачный золотой (жёсткий, отверстия под динамики) для Apple iPhone 6/6S',
        'Чехол силиконовый глянцевый с рисунком для Samsung Galaxy Note 4',
        'Чехол силиконовый глянцевый с рисунком для Samsung Galaxy Note 3',
        'Чехол силиконовый прозрачный рифленый для Apple iPhone 5/5S',
        'Чехол пластиковый с Soft Touch вставкой под дерево для Apple iPhone 6 Plus',
        'Чехол силиконовый прозрачный рифленый для Apple iPhone 6 Plus',
        'Чехол силиконовый прозрачный рифленый ромб с внутренней стороны для Apple iPhone 6/6S',
        'Чехол пластиковый с Soft Touch вставкой под дерево для Apple iPhone 4/4S и 5/5S',
        'Чехол силиконовый черный матовый для Apple iPhone 6/6S',
        'Чехол силиконовый прозрачный золотой (жёсткий, дырочки под динамики) для Apple iPhone 6 Plus',
        'Чехол пластиковый с Soft Touch вставкой под дерево для Apple iPhone 6/6S',
        'Чехол на ремень для Samsung Galaxy Note3/Note4',
        'Чехол-книжка X-level Lord III (с отделением под карточку внутри) для Apple iPhone 6/6S',
        'Чехол-книга из дерева для Samsung Galaxy Note 3',
        'Чехол S View Cover Samsung Galaxy S5',
        'Чехол Xuenair для iPhone 6 Plus',
        'Чехол S View Cover Samsung Galaxy Note 3',
        'Чехол S View Cover Samsung Galaxy S4',
        'Чехол S View Cover Samsung Galaxy S3',
        'Чехол S View Cover Samsung Alpha',
        'Чехол Samsung Galaxy Note 4 с большим окном',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin для Samsung Galaxy Note 4',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin для Apple iPhone 5/5S',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin для Samsung Galaxy S5',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin для Apple iPhone 4/4S',
        'Чехол силиконовый прозрачный ультратонкий Ultra-thin с логотипом Apple для Apple iPhone 5/5S',
    );

    public static function good()
    {
        return static::randomElement(static::$goodname);
    }
}